/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AirlineWhereUniqueInput } from "../../airline/base/AirlineWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { AirportWhereUniqueInput } from "../../airport/base/AirportWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";

@InputType()
class FlightWhereInput {
  @ApiProperty({
    required: false,
    type: () => AirlineWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AirlineWhereUniqueInput)
  @IsOptional()
  @Field(() => AirlineWhereUniqueInput, {
    nullable: true,
  })
  airline?: AirlineWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AirlineWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AirlineWhereUniqueInput)
  @IsOptional()
  @Field(() => AirlineWhereUniqueInput, {
    nullable: true,
  })
  arrivalAirport?: AirlineWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  arrivalTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  availableSeats?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => AirportWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AirportWhereUniqueInput)
  @IsOptional()
  @Field(() => AirportWhereUniqueInput, {
    nullable: true,
  })
  departureAirport?: AirportWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  departureTime?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  flightNumber?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;
}

export { FlightWhereInput as FlightWhereInput };
