/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Flight } from "./Flight";
import { FlightCountArgs } from "./FlightCountArgs";
import { FlightFindManyArgs } from "./FlightFindManyArgs";
import { FlightFindUniqueArgs } from "./FlightFindUniqueArgs";
import { CreateFlightArgs } from "./CreateFlightArgs";
import { UpdateFlightArgs } from "./UpdateFlightArgs";
import { DeleteFlightArgs } from "./DeleteFlightArgs";
import { Airline } from "../../airline/base/Airline";
import { Airport } from "../../airport/base/Airport";
import { FlightService } from "../flight.service";
@graphql.Resolver(() => Flight)
export class FlightResolverBase {
  constructor(protected readonly service: FlightService) {}

  async _flightsMeta(
    @graphql.Args() args: FlightCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Flight])
  async flights(@graphql.Args() args: FlightFindManyArgs): Promise<Flight[]> {
    return this.service.flights(args);
  }

  @graphql.Query(() => Flight, { nullable: true })
  async flight(
    @graphql.Args() args: FlightFindUniqueArgs
  ): Promise<Flight | null> {
    const result = await this.service.flight(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Flight)
  async createFlight(@graphql.Args() args: CreateFlightArgs): Promise<Flight> {
    return await this.service.createFlight({
      ...args,
      data: {
        ...args.data,

        airline: args.data.airline
          ? {
              connect: args.data.airline,
            }
          : undefined,

        arrivalAirport: args.data.arrivalAirport
          ? {
              connect: args.data.arrivalAirport,
            }
          : undefined,

        departureAirport: args.data.departureAirport
          ? {
              connect: args.data.departureAirport,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Flight)
  async updateFlight(
    @graphql.Args() args: UpdateFlightArgs
  ): Promise<Flight | null> {
    try {
      return await this.service.updateFlight({
        ...args,
        data: {
          ...args.data,

          airline: args.data.airline
            ? {
                connect: args.data.airline,
              }
            : undefined,

          arrivalAirport: args.data.arrivalAirport
            ? {
                connect: args.data.arrivalAirport,
              }
            : undefined,

          departureAirport: args.data.departureAirport
            ? {
                connect: args.data.departureAirport,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Flight)
  async deleteFlight(
    @graphql.Args() args: DeleteFlightArgs
  ): Promise<Flight | null> {
    try {
      return await this.service.deleteFlight(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Airline, {
    nullable: true,
    name: "airline",
  })
  async getAirline(@graphql.Parent() parent: Flight): Promise<Airline | null> {
    const result = await this.service.getAirline(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Airline, {
    nullable: true,
    name: "arrivalAirport",
  })
  async getArrivalAirport(
    @graphql.Parent() parent: Flight
  ): Promise<Airline | null> {
    const result = await this.service.getArrivalAirport(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Airport, {
    nullable: true,
    name: "departureAirport",
  })
  async getDepartureAirport(
    @graphql.Parent() parent: Flight
  ): Promise<Airport | null> {
    const result = await this.service.getDepartureAirport(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
